### PR TITLE
Fixes for misplaced `(identifier)` aliases & missing literals

### PR DESCRIPTION
**Pull request by LeoniePhiline**
The changes are intentionally divided into clean commits (with tests for each).

Thus, **the commits are best reviewed individually**.

This PR fixes all issues mentioned in #101.

---

I added 756ffc20c19c2cfb01c52c26938fe10b43d9fd4d as a fix for #103.

### CODE REVIEW

**Comment by LeoniePhiline** [comment]
@DerekStride Ready for review.

**Review by DerekStride — APPROVED** [review]

**Comment by matthias-Q** [comment]
The changes on `cast` and `count` will break the highlighting in nvim-treesitter

**Comment by LeoniePhiline** [comment]
@matthias-Q I assume they must be adjusted.

The highlighting can and probably should be done on a function level, see here:

https://github.com/helix-editor/helix/commit/4b30f1eecfb3801d9cb8016a3c8326b723df96f8#diff-0e56156c3c29f2784cb489d716f1779ece60bfe4c44691dbe8e6d398589c10b9

**Comment by matthias-Q** [comment]
@LeoniePhiline yes, I have a pending PR there: https://github.com/nvim-treesitter/nvim-treesitter/pull/4323

I will add these changes as well. However I would like to have it merged rather sooner than later because I keep adding changes in order to keep up with upstream changes.

@DerekStride can you do another look in that PR in order to get it approved?

**Pull request merged**
